trigger:
- main

pool: 'default'

steps:

- script: |
    cd src/
    mkdir release
    DistributionTool.exe -b -i sh.cider.streamdeck.sdPlugin -o release
  displayName: 'Run Distribution Tool'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(system.defaultWorkingDirectory)/src/release'
    ArtifactName: 'Packaged'
    publishLocation: 'Container'
